### ISSUE TITLE
Detailed instructions URLs are no longer valid

### ISSUE THREAD

**Issue by dev-tty** [chronicle/detection-rules#5]
Hi there,

It looks like these two URLs are 404'ing:

`Detection UI: https://<your chronicle instance>/docs/detection-engine/detection-engine-ui.html`
`Detection API: https://<your chronicle instance>/docs/detection-engine/detection-engine-api.html`

Thanks for publishing these!

**Comment by dev-tty** [comment]
Are the URLs no different vs what's posted publicly now:

`https://cloud.google.com/chronicle/docs/reference/detection-engine-api`

**Comment by daabr** [comment]
Thank you for the report. The documentation has indeed been migrated from customer-only visibility to public visibility, and the URLs have been modified. Will fix the links shortly.
