### ISSUE TITLE
.env Rule Manager

### ISSUE THREAD

**Issue by sat-tp** [chronicle/detection-rules#67]
Can we confirm that these placeholders/URLs are correct for interacting with the detection engine API?

The docs say differently - https://cloud.google.com/chronicle/docs/reference/detection-engine-api

**Comment by sat-tp** [comment]
Adjusting my custom code to use the v2 endpoint seems to work, but does however make this rule_cli tool unusable.

**Comment by threat-punter** [comment]
Hi there,

The rule manager tool works with the new Google SecOps [REST API](https://cloud.google.com/chronicle/docs/reference/rest), not the [Detection Engine API](https://cloud.google.com/chronicle/docs/reference/detection-engine-api).

**Comment by sat-tp** [comment]
Hi David,

I think I'm simply confused. We have some quirks to our setup in the fact we don't have access to the GCP Project that is linked to our Chronicle instance. I'll work with GCP Support to ensure the Service Account we're using as access to this API and relevant IAM permissions.

Thanks for responding. Thoroughly enjoyed your Detection-as-code talk the other week!

Sam

**Comment by threat-punter** [comment]
@sat-tp - No worries. Your Google SecOps support representative will be able to help you enable the new REST API in the Google Cloud project that's linked to your SecOps instance.

Once that's done, you can create a service account that has the required permissions to manage rules via the API.

Please let me know how you get on.

And thank you for attending my presentation 😄 

![image](https://github.com/chronicle/detection-rules/assets/56409778/5d17494a-c271-4ba4-966f-cea072780979)
